name: pitch_detection
description: A Flutter package for real-time pitch detection using YIN and MPM algorithms, optimized for musical instruments.
version: 1.0.0
homepage: https://github.com/JCHCompany/musique-signal-analyzer

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  fftea: ^1.5.0+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

topics:
  - music
  - pitch
  - detection
  - audio
  - signal-processing
  - yin
  - mpm
  - tuner